### ISSUE TITLE
Add it mplug script directory

### ISSUE THREAD

**Issue by z8512** [rozari0/DriveDownloader#2]
Mplug is like a package manager but for mpv scripts.
Please add your script there (if already not there) and also installation instructions in manifest - https://github.com/Nudin/mpv-script-directory/blob/master/HOWTO_ADD_INSTALL_INSTRUCTIONS.md

**Comment by ghost** [comment]
> Mplug is like a package manager but for mpv scripts. Please add your script there (if already not there) and also installation instructions in manifest - https://github.com/Nudin/mpv-script-directory/blob/master/HOWTO_ADD_INSTALL_INSTRUCTIONS.md

Umm, I can do that. But the thing is there are two versions of this script. One for 5.2 or older and another one for newer.
The old one is used for ubuntu-based distros.

So if I add one script on mplug that won't work for all machines.

**Comment by z8512** [comment]
Please add both version as `youtube-search` & `youtube-search-for-newer-lua` 
Please add in your readme which one to install using mplug

Thank  You

**Comment by ghost** [comment]
> Please add both version as `youtube-search` & `youtube-search-for-newer-lua` Please add in your readme which one to install using mplug
> 
> Thank You

Done, now waiting when he merge my [PR](https://github.com/Nudin/mpv-script-directory/pull/7). 
Seems he ain't actively merge PR.

**Comment by ghost** [comment]
[Merged](https://github.com/Nudin/mpv-script-directory/pull/8) .
